# Generated by Django 3.0.3 on 2020-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200228_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='email_id',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
