# Generated by Django 3.0.3 on 2020-02-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200228_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
